### ISSUE TITLE
what type of preprocessing has occured on the data?

### ISSUE THREAD

**Issue by Bart-van-Ingen** [repositoryadmin/SLERepository#1]
by plotting the data present in this repo, I suspect that preprocessing has occurred. This because none of the three axis have a mean of around 9.81, something that should be expected from an accelerometer on earth. This had me wondering, what type of preprocessing has occurred on this data set?

**Comment by repositoryadmin** [comment]
The description of the data acquisition was updated, so that includes all the relevant information.
